name: Build images-to-aws-s3

on:
  push:
    paths:
      - .github/workflows/images-to-aws-s3.yml
      - images-to-aws-s3/**
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: images-to-aws-s3
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: sam build
