name: Lint codebase

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          fetch-depth: 0
      - uses: github/super-linter/slim@45fc0d88288beee4701c62761281edfee85655d7 # v5.0.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_CLOUDFORMATION: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          MARKDOWN_CONFIG_FILE: .markdownlint.yml
